server:
  port: 8888

app:
  api-prefix: api
  api-version: v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity
          uri: http://localhost:8080
          predicates:
            - Path=/${app.api-prefix}/${app.api-version}/identity/**
          filters:
            - StripPrefix=2
        - id: profile
          uri: http://localhost:7070
          predicates:
            - Path=/${app.api-prefix}/${app.api-version}/profile/**
          filters:
            - StripPrefix=2